### ISSUE TITLE
Checkpoint should remain after undoing to it

### ISSUE THREAD

**Issue by Porrumentzio** [ogarcia/opensudoku#97] opened 2020-09-13 15:51 UTC
This allows the users to try out possible variants and if error, go back to checkpoint.
Doing this, the expected behaviour would be that the checkpoint stays there for all the game, until a new checkpoint is set. (Even then, it would be interesting to be able to set more than one checkpoint, though not very useful)

**Comment by ogarcia** [comment] 2020-09-14 11:56
The problem with this is that it collides with the current behavior because you can have more that one checkpoint

**Comment by Porrumentzio** [comment] 2020-09-14 15:35
I don't understand the problem. Could you explain further?

**Comment by ogarcia** [comment] 2020-09-15 09:38
I don't explain. The problem is that if you back to checkpoint is expected that these checkpoint will be deleted because you can have a previous checkpoint to back to it. But you can add a new checkpoint after rollback.

**Comment by Porrumentzio** [comment] 2020-09-15 13:44
But if I understand well that problem would be with more than one checkpoints, but not with the initial proposal: 

> the checkpoint stays there for all the game, until a new checkpoint is set.

**Comment by leogott** [comment] 2021-03-01 14:12
Sometimes, after having solved a sudoku part-way, I want to check why I placed a number somewhere.
In these situations it would be useful to set a checkpoint, and then undo until I undid the number and can check my logic.

Either my reasoning was wrong, and I then abandon the checkpoint to try another path, or I remember how I did it and want to return to the checkpoint again.

For this reason it would be nice if the checkpoint was seperate from the undo-history, (possibly with a warning if you want to return to the checkpoint after deviating from its history).

**Comment by ogarcia** [comment] 2022-07-25 09:41
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.

**Closed as completed by ogarcia** 2022-07-25 09:41 UTC
