### ISSUE TITLE
Menu is not accessible in Android 10

### ISSUE THREAD

**Issue by cesarizu** [ogarcia/opensudoku#36] opened 2019-09-04 06:25 UTC
Just upgraded to Android 10 and I haven't found a way to show the menu. Using the new navigation by gestures there's no gesture to show the menu. Reverting back to the 2 or 3 button navigation bar doesn't show the menu either.

**Comment by ogarcia** [comment] 2019-09-25 12:16
I cannot reproduce this issue. I try with several emulators and all of them work well.

**Comment by cesarizu** [comment] 2019-10-09 15:02
Thanks for trying. It seems that other people have noticed it too, like [here](https://www.reddit.com/r/Android/comments/d0jbpj/android_10_killed_menu_button_for_legacy_apps/). I have not found any official release notes that mentions this anywhere. The [android documentation](https://developer.android.com/guide/topics/ui/menus#options-menu) briefly mentions the menu but even the screenshots seem to be wrong there.

Is there an alternative on opensudoku to show that menu?

**Comment by ghost** [comment] 2019-11-05 18:07
I am able to reproduce this issue on Android 10, build QP1A.191005.007.A1 on a Google Pixel 1 XL.

Would it be possible to change the entry mode select button to be a menu button, or to split that button in half?

**Comment by rewolff** [comment] 2020-01-04 19:04
I have a similar issue. Since my pone's upgrade I can't access the list of problems. App just freezes. Phone becomes slow until i stop the app.

**Comment by Mark-Doe** [comment] 2020-05-02 17:34
I had the same problem today after my phone went to Android 10 last night - but with the _old_ version made by Roman Masek, still available in Play Store (20.3.2011). The menu to the bottom right is gone. In the newer version (23.03.2020) the menu button top right is working fine.

Now I have another issue importing the folder (data version 1) from the old version. Reading the code that should work but it seems that I get a SudokuInvalidFormatException - will test a bit more and open another issue. 

(Edit. the format was OK, but I had about 165 Sudokus in that folder and the last game(s, didn't count and) closing tags for Folder and openSudoku were missing. The oldest Sudokus weren't important for me so I imported 135 of them. Good enough for me.)

**Comment by rewolff** [comment] 2020-12-19 20:02
I now have a new tablet. A Samsung tab-a.  While the hint "long press the show-app-list" works on my xiaomi phone, it doesn't on this Samsung. Any suggestions on how I might access the menu?

**Comment by ogarcia** [comment] 2022-07-25 09:38
I'm migrating Open Sudoku development from GitHub to GitLab. To make the migration as clean as possible I'm going to close this issue. If you are still interested (or if it is still relevant), please open it again in [GitLab](https://gitlab.com/opensudoku/opensudoku) from July 26.

Thank you very much for your understanding.

**Closed as completed by ogarcia** 2022-07-25 09:38 UTC
Labels: help wanted
